import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'



const poppins = Poppins({ subsets: ['latin'], weight: ["300", "400", '500', '600', '700'], })

export const metadata: Metadata = {
    title: 'Planning Poker - Pragma',
    description: 'Generated by create next app',
    icons: {
        icon: [
            {
                url: '/images/favicon.webp',
            }
        ]
    }
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es">
            <body className={poppins.className}>
                {children}
            </body>
        </html>
    )
}
